apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $PROJECT_NAME
  region: us-west-2

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    amiFamily: Ubuntu2004
    # desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: $PROJECT_PEMFILE
