apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-final
  labels: 
    app: capstone-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-final
  template:
    metadata:
      labels:
        app: capstone-final
        role: rolling-update
    spec:
      containers:
      - name: capstone-final
        image: vikasgarg0385/capstone-final:new
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
