apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
  labels: 
    app: $PROJECT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      labels:
        app: $PROJECT_NAME
        role: rolling-update
    spec:
      containers:
      - name: $PROJECT_NAME
        image: $DOCKERHUB_USERID/$IMAGE_NAME:$IMAGE_VERSION
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
