# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  docker: circleci/docker@1.6.0
    
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: cimg/python:3.7.11-node
          
    working_directory: ~/repo
    
    steps:
      - checkout
      
    # Download and cache dependencies
      - restore_cache:
          keys: [capstone]
      # Create the reqiured virtual environment and install the dependent libraries
      - run:
          name: Create vitual environment
          command: |
            # Create virtual environment
            python3 -m venv ~/.capstone
            source ~/.capstone/bin/activate
      - run:
          name: Install dependencies
          command: |            
            # install nodejs, dockerio, npm, htmllint
            make install-dependencies
            
            # Install hadolint
            make install-hadolint
      - run:
          name: run lint
          command: |
            source ~/.capstone/bin/activate
            # make lint for Docker file and index.html
            make lint
      - save_cache:
          paths: [ ~/.capstone/bin/activate]
          key: capstone


  push-docker-image:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/repo      
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build & uploading the Docker image
          command: |
            # Building Docker Image
            docker build -t $DOCKERHUB_IMAGE .
            docker image ls
            
            # Upload Docker Image
            docker login -u $DOCKERHUB_USERID -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_IMAGE                      
            
  deploy-new:
    docker:
      - image: cimg/base:2021.07
      
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys: [capstone]
      - add_ssh_keys:
          fingerprints: ["3e:10:02:47:73:2f:2b:3f:a2:28:44:0c:ed:80:6a:29"]
      - run:
          name: install dependencies
          command: |
            
            # Install kubectl
            make install-kubectl
            
            # Install eksctl
            make install-eksctl
            
            # Install awscli 
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            
            aws configure list
            
            # Create Kubernetes Cluster
            make create-eks-cluster
            
            # Create deployments and Services
            make deploy-kubernetes
      - save_cache:
          paths: [ ~/.capstone/bin/activate]
          key: capstone
          
workflows:
  default:
    jobs:
#      - build
#      - push-docker-image
#          requires: [build]
      - deploy-new
#         requires: [push-docker-image]
